[package]
name = "ipupd"
version = "0.1.0"
authors = ["Julian Theis <julian.theis@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
pnet = "0.26"
serde = "1.0"
toml = "0.5"
ureq = "1.5"
